name: Run the non git integrated collection

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl https://dl-cli.pstmn.io/download/latest/linux/ -o postman-cli.tar.gz
          tar -zxvf postman-cli.tar.gz
          sudo mv postman-cli /usr/bin/postman
          rm postman-cli.tar.gz
      - name: Login to Postman CLI
        env:
          POSTMAN_API_KEY: 'PMAK-6322a364df32ad74cdd88dcc-bc3042d8d717325f2e2001b5ce65765762'
        run: postman login --with-api-key $POSTMAN_API_KEY
      - name: Run API tests
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          postman collection run "22912480-37c79db9-91d0-49fd-9cc8-3f746ae9976f" -e "22912480-8b6a2e58-45e3-4402-a912-7deea93062f3" --integration-id "122651-${GITHUB_RUN_ID}"
          # Run your API using Postman CLI
          postman api lint --integration-id 122651
